<div id="titulo" class="align-migalha">
	<h2>Download</h2>	
    <span>
	    <a class="migalha" href="<?php echo ROOT ?>Lapemm/home" title="Página principal">Home</a>|
	    <a class="migalha" href="#" title="Download">Download</a>
    </span>
    <div id="clear"></div>		
</div>

<div id="dowloads-tab">

	<div id="dowloads-col1">
		<div id="data">31</div>
		<div id="mes">JUN</div>
	</div>
	<div id="dowloads-col2">
		<h4>Plantas medicinais: A necessidade de estudos multidiciplinares</h4>
		<span class="participantes"><strong>Participantes:</strong> Jo&atilde;o Mourais, Henrique Santos e Eduardo Viera.</span>
	</div>
	
	<div id="dowloads-col3">
		<img alt="Baixar" title="Baixar" src="<?php echo PATH_TEMPLATE_URL; ?>images/pdf-icon.png"/>
	</div>
	
	<div id="clear"></div>
		
</div>

<div id="dowloads-tab">

	<div id="dowloads-col1">
		<div id="data">28</div>
		<div id="mes">JUN</div>
	</div>
	<div id="dowloads-col2">
		<h4>Plantas medicinais: A necessidade de estudos multidiciplinares</h4>
		<span class="participantes"><strong>Participantes:</strong> Jo&atilde;o Mourais, Henrique Santos e Eduardo Viera.</span>
	</div>
	
	<div id="dowloads-col3">
		<img alt="Baixar" title="Baixar" src="<?php echo PATH_TEMPLATE_URL; ?>images/pdf-icon.png"/>
	</div>
	
	<div id="clear"></div>
		
</div>