<div id="titulo" class="align-migalha">

    <h2>Grupo</h2>	

    <span> 
        <a class="migalha" href="<?php echo PATH_URL; ?>Lapemm/grupo" title="Grupo">Grupo</a>
        <a class="migalha" href="<?php echo PATH_URL; ?>Lapemm" title="Página principal">Home |</a>     
    </span>

    <div id="clear"></div>

</div>


<div>
    <div id="coluna-esquerda-grupo">				
        <div id="foto-grupo">
            <img alt="" src="<?php echo PATH_IMAGE_URL; ?>grupo/grupo.jpg"/>
        </div>
    </div>


    <div id="coluna-direita-grupo">
        <div id="conteudo">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse molestie velit in ligula vehicula nec dignissim arcu viverra. Pellentesque sagittis ornare sagittis. Aliquam erat volutpat. Donec facilisis, elit in hendrerit iaculis, elit urna adipiscing massa, vestibulum tempus ipsum mi at metus. Fusce id diam vel diam convallis interdum. Pellentesque sed ipsum in massa gravida pellentesque ut nec quam. Proin diam tellus, hendrerit eu varius interdum, venenatis ac purus. Duis velit orci, porttitor commodo sodales sed, dignissim quis diam. Ut et facilisis elit.</p>
            <p>Donec eu ante odio, id dapibus arcu. Proin placerat ornare mauris, ac posuere lectus dignissim eget. Etiam ut nisi et nibh lobortis commodo tristique vel libero. Quisque enim magna, blandit vulputate lacinia a, scelerisque malesuada ligula. Sed quis enim vitae turpis fringilla convallis. Proin nulla neque, laoreet at imperdiet nec, pellentesque ac eros. Nam ac massa non arcu mollis ultricies non in velit.</p>			
        </div>
    </div>
</div>

<div id="clear"></div>
<br />
<div id="grupo-geral">
    Conheça um pouco mais a nossa equipe. Clique na foto para ver o perfil individual de cada integrante.
    <br /><br />
    <div class="thumbnails yoxview">
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
        <a href="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png"><img src="<?php echo PATH_IMAGE_URL; ?>integrantes/default-avatar.png" alt="First" title="First image" /></a>
    </div>
    
    
</div>