<div class="home">

    <div class="enbloba-destaque">
        <div id="titulo">
            <span><a class="migalha" href="<?php echo PATH_URL; ?>index.php?Lapemm/home" title="Pagina principal">Home</a></span>
            <div id="clear"></div>
        </div>	
    </div>

    <div id="destaque">
<!--        <div class="slider">
            <img src="<?php //echo PATH_IMAGE_URL; ?>banner/img01.jpg"/>  No description 
            <img src="<?php //echo PATH_IMAGE_URL; ?>banner/img02.jpg"/><p>Description image two</p>
            <img src="<?php //echo PATH_IMAGE_URL; ?>banner/img03.jpg"/><p>Description image three</p>
        </div>-->
    </div>

    <div class="enbloga-conteudo">

        <div id="titulo">
            <!-- <div id="niver-mes" style="display: none;"> -->
            <div id="niver-mes">
                <a href="#">
                    <img alt="Aniversariante do Mês" title="Aniversariante do Mês" src="<?php echo PATH_TEMPLATE_URL; ?>images/niver-mes.png" style="border: 0px;">
                </a>
            </div>

            <div id="clear"></div>
        </div>

        <div id="coluna_1"> 
            <div class="espaco-destaque" >

                <div class="s-titulo">
                    <h3 class="titulo-noticia">Notícias</h3>
                </div>

                <div id="clear"></div>
                <div class="separador">
                    <img src="<?php echo PATH_TEMPLATE_URL; ?>images/noticias/noticia1.png" />
                    <div class="conteudo-noticia">
                        <span class="titulo-noticia">Meio Ambiente </span>
                        <p> Semana do Meio Ambiente na UFBA.</p>
                        <!--                        <a class="saiba-mais" href="#" title="Saiba Mais" target="_self">saiba mais...</a>-->
                    </div>
                </div>
                <div id="clear"></div>
                <div class="separador">
                    <img src="<?php echo PATH_TEMPLATE_URL; ?>images/noticias/noticia2.png" />
                    <div class="conteudo-noticia">
                        <span class="titulo-noticia">Workshop na UFBA</span>
                        <p>Universidade de Cambridge, faz workshop na UFBA.</p>
                        <!--                        <a class="saiba-mais" href="#" title="Saiba Mais" target="_self">saiba mais...</a>-->
                    </div>
                </div>
                <div id="clear"></div>
                <div class="separador">
                    <img src="<?php echo PATH_TEMPLATE_URL; ?>images/noticias/noticia3.png" />
                    <div class="conteudo-noticia">
                        <span class="titulo-noticia">Onda digital</span>
                        <p>Onda Digital participa de encontro em Alagoinhas.</p>
                        <!--                        <a class="saiba-mais" href="#" title="Saiba Mais" target="_self">saiba mais...</a>-->
                    </div>
                </div>
                <div id="clear"></div>
            </div>

        </div>

        <div id="coluna_2">
            <div class="espaco-destaque" id="destaque-principal"> 
                <h3>Coordenador</h3>
                <span class="mini-box">Professor Eudes Graeff,<br />coordenador de projetos <br />do  LAPPEM. </span>
                <!--                <a class="saiba-mais" href="#" title="Saiba Mais" target="_self">saiba mais...</a>-->
                <div id="coordenador"></div>
            </div>

            <div id="destaque-principal">

                <h3>Linha de Pesquisa</h3>
                <span class="mini-box">Conheçaa os tipos de linha<br />de pesquisa utilizada pelo<br />nosso laboratório.</span>
                <a class="saiba-mais" href="#" title="Saiba Mais" target="_self">saiba mais...</a>
                <div id="folha"></div>

            </div>
        </div>

        <div id="coluna_3">
            <div class="espaco-destaque" id="destaque-principal" style=" background:#DDFFEE; padding-left:1.5px; ">
                <?php //echo $view_calendario; ?>
            </div>

            <div id="destaque-principal">
                <h3>Últimos Downloads</h3>
                <span class="mini-box">Acesse aqui as nossas<br />Últimas postagens de<br />projetos para downloads</span>
                <a class="saiba-mais" href="#" title="Saiba Mais" target="_self">saiba mais...</a>
                <div id="download"></div>
            </div>
        </div>

        <div id="clear"></div>

    </div>

</div>