<div id="titulo" class="align-migalha">

    <h2>Projetos</h2>	

    <span> 
        <a class="migalha" href="<?php echo PATH_URL; ?>Lapemm/projetos" title="Projetos">Projetos</a>
        <a class="migalha" href="<?php echo PATH_URL; ?>Lapemm" title="Página principal">Home |</a>      
    </span>

    <div id="clear"></div>

</div>

<?php if (is_array($view_listProjeto)): ?>
    <?php $tProjetos = count($view_listProjeto); ?>
    <?php foreach ($view_listProjeto as $key => $objProjeto): ?>
        <div id="projeto">
            
            <h4><?php echo $objProjeto->getNome(); ?></h4>
            <p><?php echo $objProjeto->getDescricao(); ?></p>
            <span class="participantes"><strong>Integrantes:</strong> Jo&atilde;o Mourais, Henrique Santos e Eduardo Viera.</span>
            <span class="ex-integrantes"><strong>Ex-integrantes:</strong> Amanda Preira, Marcelo dos Santos e Eduardo Costa.</span>
            
            <?php if($key === ($tProjetos - 1) ): ?>
                <div id="clear" ></div>
            <?php else: ?>
                <div id="clear" class="borda"></div>
            <?php endif; ?>            
        </div>
    <?php endforeach; ?>

<?php endif; ?>

