<div id="titulo" class="align-migalha">
    <h2>Publica&ccedil;&otilde;es</h2>	
    <span>
        <a class="migalha" href="<?php echo PATH_URL; ?>index.php?Lapemm/home" title="Pagina principal">Home</a>|
        <a class="migalha" href="#" title="Publicações">Publica&ccedil;&otilde;es</a>
    </span>
    <div id="clear"></div>		
</div>

<div id="dowloads-tab">

    <div id="dowloads-col1">
        <div id="data">31</div>
        <div id="mes">JUN</div>
    </div>
    
    <div id="dowloads-col2">
        <h4>A cura pelas ervas e plantas medicinais brasileiras</h4>
       	<span class="participantes"><strong>Refer&ecirc;ncia:</strong> Ricardo Lainetti e Nei R. Seabra de Brito (Ed. Ediouro)</span>

    </div>

    <div id="dowloads-col3">
        <img alt="Baixar" title="Baixar" src="<?php echo PATH_TEMPLATE_URL; ?>images/pdf-icon.png"/>
    </div>

    <div id="clear"></div>

</div>

<div id="dowloads-tab">
    
    <div id="dowloads-col1">
        <div id="data">31</div>
        <div id="mes">JUN</div>
    </div>

    <div id="dowloads-col2">
        <h4>Plantas Medicinais e benzeduras</h4>
       	<span class="participantes"><strong>Refer&ecirc;ncia:</strong> Teo Azevedo (Ed. Top Livros)</span>

    </div>

    <div id="dowloads-col3">
        <img alt="Baixar" title="Baixar" src="<?php echo PATH_TEMPLATE_URL; ?>images/pdf-icon.png"/>
    </div>

    <div id="clear"></div>

</div>