<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Integrante<small>informações</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <?php echo $view_toolbar; ?>
            <div class="page-control" data-role="page-control">
                
                <ul>
                    <li class="active"><a href="#frameI">Identificação</a></li>
                </ul>
                
                <div class="frames">
                    
                    <div class="frame active" id="frameI">
                        <h2>Nome:</h2>
                        <?php echo $view_objIntegrante->getNome(); ?>
                        <h2>Número CPF</h2> 
                        <?php echo $view_objIntegrante->getCpf(); ?>
                        <h2>Data Nascimento</h2>
                        <?php echo $view_objIntegrante->getDataNascimento(); ?>
                        <h2>Email </h2>
                        <?php echo $view_objIntegrante->getEmail(); ?>
                        <h2>Número Telefone (Fixo)</h2>
                        <?php echo ($view_objIntegrante->getNumeroTelefone() === null) ? 'Não Informado' : $view_objIntegrante->getNumeroTelefone(); ?>
                        <h2>Número Telefone (Celular)</h2>
                        <?php echo ($view_objIntegrante->getNumeroCelular() === null) ? 'Não Informado' : $view_objIntegrante->getNumeroCelular(); ?>
                        <h2>Curriculo Lattes</h2>
                        <?php echo $view_objIntegrante->getLattes(); ?>
                        <h2>Titulação</h2>
                        <?php echo ($view_objIntegrante->getTitulacao()->getNome() == null) ? 'Não Informado': $view_objIntegrante->getTitulacao()->getNome(); ?>                            
                        <h2>Status</h2>
                        <?php echo $view_objIntegrante->getStatus() == "A" ? "Ativo" : "Desativado"; ?>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
