</div><!-- FIM DIV - <div id="principal"> -->

</div><!-- FIM DIV - <div id="container-contents"> -->

<div id="container-footer">

    <div id="container-mapa">

        <div class="principal">

            <div id="mapa">
                 <div class="colunas">
                    <ul>
                    	
                        <div class="titulo-links">Ensino de Química</div>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Ensino de Química">CNPq</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Ensino de Química">PPGFAR-UFBA</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Ensino de Química">SBFG</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Ensino de Química">LAEQUI</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Ensino de Química">PUBMED</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Ensino de Química">NATURAL PRODUCTS</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Ensino de Química">SCICENCE</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Ensino de Química">PHARMACEUTICAL SCIENCES</a></li>
                    
                    </ul>
                </div>
                <div class="colunas">
                    <ul>
                        <!--<div class="titulo-links">::  Links Relacionados</div>-->
                        <div class="titulo-links">Análise Clínica</div>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa e Análises Clínicas">UFBA</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa e Análises Clínicas">FAPESB</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa e Análises Clínicas">PHYTOCHEMISTY</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa e Análises Clínicas">NATURE</a></li>
                        
                         <div class="titulo-links">Microbiologia</div>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Microbiologia">KEGG PATHWAY</strong></a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa em Microbiologia">FINEP</strong></a></li>
                        
                      </ul>
                </div>

               

                <div class="colunas">
                    <ul>
                        <!--<div class="titulo-links">&nbsp;</div>-->
                       	<div class="titulo-links">Produtos Naturais</div>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa de Produtos Naturais">SBQ</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa de Produtos Naturais">SICFINDER</a></li>
                     	<li> <a href="" target="_blank" title="Laboratório de Pesquisa de Produtos Naturais">FINEP</a></li>
                        <li> <a href="" target="_blank" title="Laboratório de Pesquisa de Produtos Naturais">COMUT</a></li>
                       
                    </ul>
                </div>
            </div>

            <div id="contato">

                <p>
                    Para sugestões, dúvidas, ou qualquer outro 
                    assunto referente a Projeto de Pesquisa,
                    entrar em contato conosco através do email euvelozo@ufba.br ou pelo número:
                </p>

                <!--<div>
                    <span id="email">E-mail:  - Eudes Velozo</span>
                </div>-->

                <div>
                    <span id="tel">71 3283.6930/6966</span>
                </div>
                
                <div id="logo-brasao">
                    <img alt="" title="" src="<?php echo PATH_TEMPLATE_URL; ?>images/logo-brasao.png" />
                </div>
                
            </div>

            <div id="clear"></div>

        </div>

    </div>	

    <div id="container-rodape">
        <div class="principal" id="rodape">
            <div id="menu-rodape">
                <ul>
                    <li><a href="<?php echo PATH_URL; ?>/Lapemm/home">Home</a>|</li>
                    <li><a href="<?php echo PATH_URL; ?>/Lapemm/quemsomos">LAPEMM</a>|</li>
                    <li><a href="<?php echo PATH_URL; ?>/Lapemm/grupo">Grupo</a>|</li> 
                    <li><a href="<?php echo PATH_URL; ?>/Lapemm/projetos">Projetos</a>|</li>
                    <li><a href="<?php echo PATH_URL; ?>/Lapemm/publicacoes">Publicações</a> |</li> 
                    <li><a href="<?php echo PATH_URL; ?>/Lapemm/galeria">Galeria</a>|</li> 
                    <li><a href="<?php echo PATH_URL; ?>/Lapemm/download">Download</a></li>
                </ul>
            </div>
            <div id="clear"></div>
            <span>  Copyright 2012 &copy; LAPEMM - Todos os direitos reservados.</span>
        </div>
    </div>

</div>