<style>
.fb_edge_widget_with_comment {
    float: right;
    padding-top: 20px;
    margin-right: 5px;
    position: relative;
}
#google-mais{
	float:right; 
	padding-top: 20px;
        margin-right: -25px;
}
</style>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Place this tag where you want the +1 button to render. -->


<!--Google+-->

<!-- Place this tag after the last +1 button tag. -->
<script type="text/javascript">
  window.___gcfg = {lang: 'pt-BR'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>


<div id="container-header">

    <div id="topo">

        <div id="container-topo-cima">


            <div class="principal">

                <!--Plugin FaceBook-->            
                <div class="fb-like" data-href="http://www.lapemm.ufba.br" data-send="true" data-layout="button_count" data-width="460" data-show-faces="true" data-font="trebuchet ms"></div>   
                <!--Plugin Google + -->  
                <div id="google-mais">  
                	<div class="g-plusone" data-size="medium" data-href="http://www.lapemm.ufba.br"></div>
                </div>
<!--                <span class="infor-topo-texto">PNCQ 00453  -  ISO9001:2000</span>-->
            
            </div>
            
        </div>

        <div id="container-menu">

            <div class="principal">

                <div id="logo">
                    <a href="<?php echo PATH_URL; ?>index.php?Lapemm/home"><img alt="LAPEMM" title="LAPEMM" src="<?php echo PATH_TEMPLATE_URL; ?>images/logo.png" style="border: 0px;"></a>
                </div>

                <div id="menu">

                    <ul>
                        <li><a href="<?php echo PATH_URL; ?>index.php?Lapemm/home">Home</a></li>
                        <li><a href="<?php echo PATH_URL; ?>index.php?Lapemm/quemsomos">Lapemm</a></li>
                        <li><a href="<?php echo PATH_URL; ?>index.php?Lapemm/grupo">Grupo</a></li>
                        <li><a href="<?php echo PATH_URL; ?>index.php?Lapemm/projetos">Projetos</a></li>
                        <li><a href="<?php echo PATH_URL; ?>index.php?Lapemm/publicacoes">Publica&ccedil;&otilde;es</a></li>
                        <li><a href="<?php echo PATH_URL; ?>index.php?Lapemm/galeria">Galeria</a></li>
                        <li><a href="<?php echo PATH_URL; ?>index.php?Lapemm/download">Download</a></li>
                    </ul>

                </div>

                <div id="shadow"></div>

                <div id="clear"></div>

            </div>

        </div>

    </div>

</div>


<div id="container-contents"> <!-- INICIO DIV - <div id="container-contents"> -->

    <div class="principal">	<!-- INICIO DIV - <div id="principal"> -->