<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Cadastro<small>Projeto</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <form name="fCadastro" id="fCadastro" action="index.php?Projeto/inserir" method="post">

                <h2>Nome *</h2>
                <div class="input-control text">
                    <input type="text" name="nome" id="nome" maxlength="120"  required=""/>
                </div>
                
                <h2>Linha de Pesquisa *</h2>
                <div class="input-control select">
                    <select id="perfil" name="linhaDePesquisa" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php
                            echo $view_listLinhaDePesquisa;
                        ?>
                    </select>
                </div>
                
                <h2>Descrição *</h2>
                <div class="input-control textarea">
                    <textarea name="descricao" id="descricao" required="" maxlength="250"></textarea>
                </div>

                <h2>Publicação *</h2>
                <div class="input-control textarea">
                    <textarea cols="100" rows="16" id="txEditor" name="publicacao" id="publicacao" required=""></textarea>
                </div>

                <input type="submit" value="Salvar">

            </form>
        </div>
    </div>
</div>