<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Projeto<small>informações</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <?php echo $view_toolbar; ?>
            <div class="page-control" data-role="page-control">
                
                <ul>
                    <li class="active"><a href="#frameI">Identificação</a></li>
                    <li><a href="#frameP">Publicação</a></li>
                </ul>
                
                <div class="frames">
                    
                    <div class="frame active" id="frameI">
                        <h2>Nome</h2>
                        <?php echo $view_objProjeto->getNome(); ?>
                        <h2>Descricao</h2>
                        <?php echo $view_objProjeto->getDescricao(); ?>
                        <h2>Linha de Pesquisa</h2>
                        <?php echo $view_objProjeto->getLinhaDePesquisa()->getNome(); ?>
                    </div>
                    
                    <div class="frame" id="frameP">
                        <h2>Conteudo Publicado (WebSite)</h2>
                        <hr><br />
                        <?php echo $view_objProjeto->getPublicacao(); ?>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
