<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Projeto<small>lista</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>

    <div class="page-region">
        <div class="page-region-content">

            <div>
                <?php echo $view_toolbar; ?>    
            </div>

            <?php if (is_array($view_listProjeto)): ?>

                <table class="striped">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Descrição</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($view_listProjeto as $objProjeto) : ?>

                            <tr>
                                <td>
                                    <a href="index.php?Projeto/informar/id/<?php echo $objProjeto->getId(); ?>">
                                        <?php echo FormatHelper::convertMaiusculo($objProjeto->getNome()); ?>
                                    </a>
                                </td>
                                <td>
                                    <?php echo $objProjeto->getDescricao(); ?>
                                </td>
                            </tr>

                        <?php endforeach ?>
                    </tbody>
                    <tfoot></tfoot>
                </table>

            <?php else: ?>
                <h3>Nenhuma Projeto encontrado.</h3>
            <?php endif; ?>
        </div>
    </div>
</div>