<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Cadastro<small>Usuário</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <form name="fCadastro" id="fCadastro" action="index.php?Usuario/inserir" method="post">

                <h2>Nome *</h2>
                <div class="input-control text">
                    <input type="text" name="nome" id="nome" maxlength="115" required=""/>
                </div>

                <h2>Email *</h2>
                <div class="input-control text">
                    <input type="text" name="email" id="email" maxlength="115" required=""/>
                </div>
                
                <h2>Perfil *</h2>
                <div class="input-control select">
                    <select id="perfil" name="perfil" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php
                        echo $view_listPerfil;
                        ?>
                    </select>
                </div>
                
                <input type="submit" value="Salvar">
            </form>
        </div>
    </div>
</div>