<script type="text/javascript">
    $(function(){
        $('#fCadastro').populate(<?php echo $view_json_objeto; ?>);
    });      
</script>
<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Editar<small>Usuário</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <form name="fCadastro" id="fCadastro" action="index.php?Usuario/atualizar" method="post">

                <input type="hidden" name="id" id="id"/>

                <h2>Nome *</h2>
                <div class="input-control text">
                    <input type="text" name="nome" id="nome" maxlength="115" required=""/>
                </div>

                <h2>Email *</h2>
                <div class="input-control text">
                    <input type="text" name="email" id="email" maxlength="115" required=""/>
                </div>

                <h2>Perfil *</h2>
                <div class="input-control select">
                    <select id="perfil" name="perfil" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php
                        echo $view_listPerfil;
                        ?>
                    </select>
                </div>

                <input type="submit" name="editar" value="Salvar">
            </form>
        </div>
    </div>
</div>